### ISSUE TITLE
it would be nice to put the information on the page that what month of the year the video has recorded/released

### ISSUE THREAD

**Issue by hokugawa** [AdobeDocs/analytics-learn.en#14]
Issue in ./help/analysis-workspace/visualizations/visualization-types.md

Some videos are introducing new features for a specific release. like this video says new visualization implemented in June release. However, it lacks information on which year of June.

**Comment by mugdoor** [comment]
Thank you for your feedback. We will be updating many of these videos, and in them removing the explanation of when certain features released. We think that it's more important to just learn how to use a feature rather than worry about when it came out.
That being said, I'm sure that Product Management will still convey feature releases out to customers and partners.
Thanks again!
Doug
